server:
  port: 3000

spring:
  application:
    name: grafana-webhook

  mail:
    host: smtp.gmail.com
    port: 587
    username: 
    password: 
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  amqp:
    deserialization:
      trust:
        all: true

grafana:
  base-url: https://mevin.online/grafana 
  api-key: 